namespace Dapper.Wrapper.Test.Models
{
    using SqlManager;
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProductModel")]
    public class ProductModel : BaseEntityWithNameAndAutoGeneratedId
    {
        [Key]
        [Column("ProductModelID")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public override int Id { get; set; }

        public Guid? rowguid { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}
