namespace Dapper.Wrapper.SqlManager
{
    /// <summary>
    /// An abstract base class for entities with an automatically generated identifier and a name.
    /// This class extends <see cref="BaseEntityWithAutoGeneratedId"/>, adding a 'Name' property to it.
    /// It is designed to be a base for entities where both an auto-generated ID and a name are common properties.
    /// </summary>
    public abstract class BaseEntityWithNameAndAutoGeneratedId : BaseEntityWithAutoGeneratedId
    {
        /// <summary>
        /// Gets or sets the name of the entity. The name can be null or empty, indicating that
        /// the entity might not always require a name to be specified.
        /// </summary>
        public virtual string? Name { get; set; }
    }

}