namespace Dapper.Wrapper.SqlManager
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// An abstract base class for entities with an automatically generated identifier.
    /// This class provides a common ID property that is auto-incremented by the database,
    /// serving as the primary key for any derived entity classes.
    /// </summary>
    public abstract class BaseEntityWithAutoGeneratedId
    {
        /// <summary>
        /// Gets or sets the primary key for the entity which is automatically
        /// generated by the database upon insertion. This property is marked as
        /// the key and is configured to use the database's identity mechanism
        /// for generating its value.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual int Id { get; set; }
    }

}